### ISSUE TITLE
Api not working..

### ISSUE THREAD

**Issue by sumeetbits** [typepad/php-typepad-api#2]
Hello,

I have downloaded and integrated the api according to docs but it is giving me error as 

Warning: require_once(BatchRequest.php) [function.require-once]: failed to open stream: No such file or directory in E:\wamp\www\PM6\project123\working\development\version1\typepad\lib\TypePad.php on line 800

Fatal error: require_once() [function.require]: Failed opening required 'BatchRequest.php' (include_path='.;C:\php5\pear;E:\wamp\www\PM6\project123\working\development\version1\typepad\lib\;E:\wamp\www\PM6\project123\working\development\version1\typepad\lib\') in E:\wamp\www\PM6\project123\working\development\version1\typepad\lib\TypePad.php on line 800

BatchRequest.php file is in extlib folder..

Does api has some bug?

**Comment by kshay** [comment]
The TypePad library attempts to add both lib and extlib to PHP's include path using the set_include_path() function (see lines 796-8 of TypePad.php), so it looks like that's not working on your system for some reason.

The notes on http://php.net/manual/en/function.set-include-path.php mention a few different reasons why it might not work--maybe you could see if any of those apply in your case?

**Comment by sumeetbits** [comment]
Thanks.. Its working now..
